#!/usr/bin/env bash

SERVER=${1:-discover}
INPUT=./data/derived/ht-trait-inputs
if [ "$SERVER" = "discover" ]; then
    rsync -avz --progress \
        $INPUT \
        discover:~/projects/sbg-uncertainty/isofit/examples/py-hypertrace/
elif [ "$SERVER" = "adapt" ]; then
    rsync -avz --progress \
        $INPUT \
        adapt:~/projects/sbg-uncertainty/isofit/examples/py-hypertrace/
else
    echo "Unkonwn server"
    exit 1
fi
